name: Code analysis

on:
  push:
    branches-ignore: [main]
    paths:
      - 'src/**'
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.mjs'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/code-analysis
